language: node_js

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - g++-4.8

before_install:
    - export CXX="g++-4.8"
    - npm install juttle@>=0.4.0

node_js:
    - '4.2'
    - '5.0'

script:
    - npm test
    - npm run test-coverage
    - npm run check-coverage
